---
clone:
  depth: 1
kind: pipeline
name: AzurePipeline
steps:
  -
    commands:
      - "export token=$TOKEN"
      - "curl https://raw.githubusercontent.com/KazuDante89/kernel_sdm660_tempest-4.4/r4/build.sh | bash"
    environment:
      TOKEN:
        from_secret: token
    image: panchajanya1999/archlinux:latest
    name: Azure-Images
    trigger:
      branch:
        - r4
